# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17e1f47fab3d72d48cbb70300371b63b4f0275c1a202104918ff47621f94e90a2feba9d4b0169f0e238859ff76ea4dd9efa55c2e35b3b54abb34048732baab7

test:
  secret_key_base: 82d1c0419d31d0f0d86189acda083308f05b74f2c6b565a6507b06582411705a4eb5e62fc19822d8ca134f2b21399140e09ca3266c61ceef1e1aee6d770b80f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
